# Generated by Django 2.0.6 on 2018-09-16 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='painting',
            options={'ordering': ('name',), 'verbose_name': 'painting', 'verbose_name_plural': 'paintings'},
        ),
    ]
