# Generated by Django 2.0.6 on 2018-09-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0002_auto_20180916_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='dimension',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(upload_to='product'),
        ),
    ]
