# Generated by Django 2.0.6 on 2018-09-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0003_auto_20180927_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='dimension',
            field=models.CharField(max_length=250),
        ),
    ]
