# Generated by Django 2.0.6 on 2018-09-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
