# Generated by Django 2.0.6 on 2018-10-01 16:06

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180927_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image_created', models.DateTimeField(auto_now_add=True)),
                ('product_image_updated', models.DateTimeField(auto_now=True)),
                ('product_image', imagekit.models.fields.ProcessedImageField(upload_to='product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.Product')),
            ],
            options={
                'verbose_name': 'product-image',
                'verbose_name_plural': 'products-images',
                'ordering': ('-product_image_created',),
            },
        ),
    ]
